
print('**********************************************************')
print('')
print('*                   Machine Problem 1                      *')
print('')
print('*                  Fundamentals in Programming             *')
print('')
print('*            Programmer: Arden Roland Nicholai M. Austria  *')
print('')
print('*            Professor: Jasmin H. Almarinez                *')
print('')
print('*            Due date: September 9, 2023                   *')
print('')
print('*            Email-address: ladew_jasmin@yahoo.com         *')
print('')
print('**********************************************************')
print('')
print('')
print('       ****     *****  *****        ******   ')
print('')
print('       ****     *****  *****       ********')
print('')
print('       ****     ************      ***    ***')
print('')
print('****   ****     ************     ************')
print('')
print('****   ****     *****  *****     ************')
print('')
print(' **********     *****  *****     ****    ****')
print('')
print('  ********      *****  *****     ****    ****')
print('')
